import { PrismaClient } from "@prisma/client";
const p = new PrismaClient();

const events = [
    {
        id: "EVT-001",
        title: "Memorial Tournament for the Late Ansumana Kamara",
        date: "2026-03-15",
        time: "09:00 AM",
        location: "Freetown Chess Club, Freetown",
        type: "Tournament",
        level: "National",
        status: "Upcoming",
        organizer: "Sierra Leone Chess Federation",
        description: "A solemn and prestigious memorial tournament honoring the life and legacy of the late Ansumana Kamara, one of Sierra Leone's greatest chess masters. Players from across the country gather to celebrate his contributions to chess.",
        image: "/images/events/memorial-tournament.png",
        registrationOpen: true,
        prizePool: "SLL 5,000,000",
        entryFee: "SLL 50,000",
    },
    {
        id: "EVT-002",
        title: "National Chess Championship",
        date: "2026-04-10",
        time: "08:00 AM",
        location: "Bintumani Conference Centre, Freetown",
        type: "Championship",
        level: "National",
        status: "Upcoming",
        organizer: "Sierra Leone Chess Federation",
        description: "The premier annual chess competition in Sierra Leone. Top players from all regions compete for the national title, with FIDE rating points on the line. Open to all registered SLCF members.",
        image: "/images/events/national-championship.png",
        registrationOpen: true,
        prizePool: "SLL 20,000,000",
        entryFee: "SLL 100,000",
    },
    {
        id: "EVT-003",
        title: "Zone 4.2 Tournament",
        date: "2026-05-20",
        time: "09:00 AM",
        location: "Freetown, Sierra Leone",
        type: "Tournament",
        level: "International",
        status: "Upcoming",
        organizer: "Africa Chess Confederation / SLCF",
        description: "FIDE Zone 4.2 qualifying tournament bringing together chess players from West African nations. Sierra Leone hosts this prestigious continental event, with qualification spots for the next FIDE World Championship cycle at stake.",
        image: "/images/events/zone42-tournament.png",
        registrationOpen: true,
        prizePool: "USD 10,000",
        entryFee: "USD 50",
    },
    {
        id: "EVT-004",
        title: "Inter-School Chess Tournament",
        date: "2026-06-07",
        time: "09:00 AM",
        location: "Annie Walsh Memorial School, Freetown",
        type: "Tournament",
        level: "Scholastic",
        status: "Upcoming",
        organizer: "Sierra Leone Chess Federation",
        description: "Annual scholastic chess competition for primary and secondary school students across Sierra Leone. Designed to promote chess in schools and identify young talent, with trophies and scholarships for top finishers.",
        image: "/images/events/interschool-chess.png",
        registrationOpen: true,
        prizePool: "Trophies & Scholarships",
        entryFee: "Free",
    },
    {
        id: "EVT-005",
        title: "Village School Chess Outreach",
        date: "2026-07-01",
        time: "10:00 AM",
        location: "Koinadugu, Kenema & Kailahun Districts",
        type: "Community",
        level: "National",
        status: "Upcoming",
        organizer: "Sierra Leone Chess Federation",
        description: "Bringing the royal game to every corner of Sierra Leone. Our outreach program delivers high-quality chess sets and professional coaching to rural village schools, empowering the next generation of strategic thinkers from the grassroots up.",
        image: "/images/events/village-school-chess.png",
        registrationOpen: false,
        prizePool: null,
        entryFee: null,
    },
    {
        id: "EVT-006",
        title: "Annual General Meeting (A.G.M)",
        date: "2026-08-15",
        time: "10:00 AM",
        location: "SLCF Headquarters, Freetown",
        type: "Meeting",
        level: "National",
        status: "Upcoming",
        organizer: "Sierra Leone Chess Federation",
        description: "The Annual General Meeting of the Sierra Leone Chess Federation. All affiliated clubs, officials, and stakeholders are invited to review the year's activities, financial reports, and plan for the upcoming chess calendar.",
        image: "/images/events/national-championship.png",
        registrationOpen: false,
        prizePool: null,
        entryFee: null,
    },
    {
        id: "EVT-007",
        title: "Congress (Elections)",
        date: "2026-09-20",
        time: "09:00 AM",
        location: "Country Lodge Hotel, Freetown",
        type: "Congress",
        level: "National",
        status: "Upcoming",
        organizer: "Sierra Leone Chess Federation",
        description: "SLCF quadrennial congress for the election of new federation officials. All registered member clubs are eligible to vote. Candidates for President, Secretary General, and other executive positions will be announced prior to the congress.",
        image: "/images/events/slcf-congress.png",
        registrationOpen: false,
        prizePool: null,
        entryFee: null,
    },
    {
        id: "EVT-008",
        title: "Chess Olympiad",
        date: "2026-09-01",
        time: "10:00 AM",
        location: "Tashkent, Uzbekistan",
        type: "International",
        level: "International",
        status: "Upcoming",
        organizer: "FIDE / Sierra Leone Chess Federation",
        description: "Sierra Leone national chess teams (Open and Women) compete at the FIDE Chess Olympiad representing the nation on the world stage. The biennial Olympiad is the most prestigious team chess event in the world.",
        image: "/images/events/chess-olympiad.png",
        registrationOpen: false,
        prizePool: null,
        entryFee: null,
    },
    {
        id: "EVT-009",
        title: "Chess Education Program",
        date: "2026-10-05",
        time: "09:00 AM",
        location: "Multiple Schools, Freetown & Provinces",
        type: "Education",
        level: "National",
        status: "Upcoming",
        organizer: "Sierra Leone Chess Federation",
        description: "A structured chess education initiative introducing chess as a cognitive development tool in schools across Sierra Leone. Trained coaches will visit participating schools to teach students chess fundamentals, strategy, and sportsmanship.",
        image: "/images/events/chess-education.png",
        registrationOpen: true,
        prizePool: null,
        entryFee: "Free",
    },
];

async function run() {
    for (const ev of events) {
        await p.calendarEvent.upsert({
            where: { id: ev.id },
            update: ev,
            create: ev,
        });
        console.log("Inserted:", ev.title);
    }
    console.log("All 9 events inserted!");
    process.exit(0);
}

run().catch(e => { console.error(e); process.exit(1); });
